"""init

Revision ID: bf59d3b6c7f2
Revises: 
Create Date: 2022-09-14 18:41:12.239115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf59d3b6c7f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_name', sa.String(length=100), nullable=True, comment='用户名'),
    sa.Column('answer_title', sa.String(length=100), nullable=True, comment='答案文件名'),
    sa.Column('answer_detail', sa.Text(length=100), nullable=True, comment='答案详情'),
    sa.Column('answer_result', sa.Text(length=100), nullable=True, comment='答案结果'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='回答时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('username', sa.String(length=20), nullable=True, comment='用户名'),
    sa.Column('hashed_password', sa.String(length=300), nullable=True, comment='密码'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('full_name', sa.String(length=100), nullable=True, comment='全名'),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='回答时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('score')
    # ### end Alembic commands ###
